# Build stage 1.
# The instructions for the development stage
FROM node:12.19.0-alpine3.9 

ENV NODE_ENV=development

WORKDIR /usr/src/app
COPY . .
RUN yarn install
RUN yarn build

COPY . .
EXPOSE 9000

CMD [ "sh","entrypoint.bash" ]