version: '3.8'

services:
  sqldb:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c "yarn db:create;"
    volumes:
      - ./:/usr/src/app/
    ports:
      - ${PORT}:7000
    env_file:
      - .env
    depends_on:
      - db
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c "yarn db:migrate; yarn start:dev"
    volumes:
      - ./:/usr/src/app/
    ports:
      - ${PORT}:7000
    env_file:
      - .env
    depends_on:
      - db

  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:7000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres_data: null
